# Generated by Django 3.1.6 on 2021-11-04 18:41

import cms.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='files/', verbose_name='Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='File uploaded at')),
                ('order', cms.fields.OrderField(blank=True, verbose_name='Order #')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('username', models.CharField(max_length=90, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('date_bought', models.DateTimeField(blank=True, null=True, verbose_name='Date Bought')),
                ('order', cms.fields.OrderField(blank=True, verbose_name='Order #')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ('order', '-date_bought'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='Team')),
                ('establishment_date', models.DateField(null=True, verbose_name='Established on')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price in €')),
                ('players', models.IntegerField(blank=True, null=True, verbose_name='Players')),
                ('league', models.PositiveSmallIntegerField(choices=[(1, 'Premier-League'), (2, 'LaLiga'), (3, 'I.S.L')], default=3, verbose_name='League')),
                ('rank', cms.fields.OrderField(blank=True, verbose_name='Rank #')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['rank'],
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='documents',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
    ]
