# Generated by Django 3.1.6 on 2021-11-04 18:50

import cms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20211104_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=cms.fields.OrderField(blank=True, default=None, verbose_name='Order #'),
        ),
    ]
