# Generated by Django 3.1.6 on 2021-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211104_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, default='#', max_length=50),
        ),
    ]
